POST http://localhost/api/backoffice/{{tenant}}/security/role-permissions
accept: application/json
content-type: application/json
Authorization: Bearer {{token}}

{
    "roleId": 1,
    "permissionId": 19
}

###
