POST http://localhost/api/register
accept: application/json
content-type: application/json

{
    "name": "Example Developer",
    "email": "email@medine.tech",
    "password": "password",
    "password_confirmation": "password"
}

###
