POST http://localhost/api/backoffice/{{tenant}}/accounting/accounting-centers
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "id": "{{$random.uuid}}",
    "code": "AC-{{$random.number}}",
    "name": "{{$random.company}}",
    "description": "{{$random.lorem.sentence}}",
    "status": "active",
    "parent_id": "{{$random.uuid}}",
    "company_id": "{{$random.uuid}}"
}
