GET http://localhost/api/backoffice/{{tenant}}/accounting/accounting-centers/24679aa3-fc51-4a63-9b9d-83db7b83a96d
accept: application/json
Authorization: Bearer {{token}}

#####

#GET http://localhost/api/backoffice/{{tenant}}/accounting/accounting-centers
#accept: application/json
#Authorization: Bearer {{token}}
#
####
