POST http://localhost/api/backoffice/first-companies
accept: application/json
content-type: application/json

{
    "companyId": "{{$uuid}}",
    "companyName": "{{$random.company.name}}",
    "name": "{{$random.alphabetic(10)}}",
    "email": "email1@example.com",
    "password": "password",
    "password_confirmation": "password"
}

###
