/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RegisterImport } from './routes/register'
import { Route as LoginImport } from './routes/login'
import { Route as R404Import } from './routes/$404'
import { Route as IndexImport } from './routes/index'
import { Route as CompanyIdDashboardImport } from './routes/$companyId.dashboard'

// Create/Update Routes

const RegisterRoute = RegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const R404Route = R404Import.update({
  id: '/$404',
  path: '/$404',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CompanyIdDashboardRoute = CompanyIdDashboardImport.update({
  id: '/$companyId/dashboard',
  path: '/$companyId/dashboard',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$404': {
      id: '/$404'
      path: '/$404'
      fullPath: '/$404'
      preLoaderRoute: typeof R404Import
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/$companyId/dashboard': {
      id: '/$companyId/dashboard'
      path: '/$companyId/dashboard'
      fullPath: '/$companyId/dashboard'
      preLoaderRoute: typeof CompanyIdDashboardImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$404': typeof R404Route
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/$companyId/dashboard': typeof CompanyIdDashboardRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$404': typeof R404Route
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/$companyId/dashboard': typeof CompanyIdDashboardRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$404': typeof R404Route
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/$companyId/dashboard': typeof CompanyIdDashboardRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$404' | '/login' | '/register' | '/$companyId/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$404' | '/login' | '/register' | '/$companyId/dashboard'
  id:
    | '__root__'
    | '/'
    | '/$404'
    | '/login'
    | '/register'
    | '/$companyId/dashboard'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  CompanyIdDashboardRoute: typeof CompanyIdDashboardRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  CompanyIdDashboardRoute: CompanyIdDashboardRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$404",
        "/login",
        "/register",
        "/$companyId/dashboard"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$404": {
      "filePath": "$404.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/$companyId/dashboard": {
      "filePath": "$companyId.dashboard.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
