POST http://localhost/api/backoffice/{{tenant}}/companies
accept: application/json
content-type: application/json
Authorization: Bearer {{token}}

{
  "id": "{{$random.uuid}}",
  "name": "{{$random.alphabetic(10)}}"
}

###
