PUT http://localhost/api/backoffice/{{tenant}}/companies/3357d6a7-adec-49c2-a3fe-f97e6a09c6a1
accept: application/json
content-type: application/json
Authorization: Bearer {{token}}

{
  "name": "{{$random.company.name}}"
}
