GET http://localhost/api/backoffice/users/3
accept: application/json
Authorization: Bearer {{token}}

###

GET http://localhost/api/backoffice/users
accept: application/json
Authorization: Bearer {{token}}

###
