POST http://localhost/api/backoffice/{{tenant}}/users
accept: application/json
content-type: application/json
Authorization: Bearer {{token}}

{
  "name": "{{$random.name.fullName}}",
  "email": "{{$random.email}}",
  "password": "{{$random.internet.password}}"
}
